# trigger:
#   branches:
#     include:
#     - main

jobs:
- job: buildandtest
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      sudo apt update
      sudo apt install -y wget
      wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
      tar -xvf gitleaks.tar.gz
      sudo mv gitleaks /usr/local/bin/
      rm gitleaks.tar.gz
      gitleaks detect --source=. --exit-code 126 --verbose --redact --report-format junit --report-path=$(Common.TestResultsDirectory)/gitleaks --format template --template "@template/junit.tpl"

    displayName: 'Detect Secrets - Gitleaks'
    continueOnError: true
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-report-low-med.xml'
      mergeTestResults: true
      failTaskOnFailedTests: false
      testRunTitle: 'Trivy - Low and Medium Vulnerabilities'
    condition: 'always()'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-report-high-crit.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'Trivy - High and Critical Vulnerabilities'
    condition: 'always()'
