# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'wellpast/devsecops-backend'
    command: 'build'
    dockerfile: 'backend/backend-service.dockerfile'
    buildContext: '$(Build.SourcesDirectory)/backend'
    tags: |
        latest

- task: CmdLine@2
  displayName: Find CVEs on image
  inputs:
    script: |
      # Install the Docker Scout CLI
      curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
      # Login to Docker Hub required for Docker Scout CLI
      docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PAT)
      # Get a CVE report for the built image and fail the pipeline when critical or high CVEs are detected
      docker scout cves wellpast/devsecops-backend:latest --exit-code --only-severity critical,high
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'wellpast/devsecops-backend'
    command: 'push'
    tags: |
        latest